services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: qbittorrent_gluetun
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 6881:6881
      - 6881:6881/udp
    volumes:
      - /docker/qbittorrent/gluetun-data:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - VPN_TYPE=${VPN_TYPE}
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - OPENVPN_CIPHERS=${OPENVPN_CIPHERS}
      - SERVER_REGIONS=${SERVER_REGIONS}
      - SERVER_CITIES=${SERVER_CITIES}
      # Timezone for accurate log times
      - TZ=${TIMEZONE}

  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      - WEBUI_PORT=8888
      # - DOCKER_MODS=ghcr.io/gilbn/theme.park:qbittorrent
      # - TP_THEME=dracula
    volumes:
      - /docker/qbittorrent/qbittorrent-config:/config
      - /media/downloads:/downloads
      # edit watched_folders.json to set watch folders associated with categories
      - /media/j:/j
      - /etc/localtime:/etc/localtime:ro
