services:
  maintainerr:
    image: ghcr.io/maintainerr/maintainerr:latest # or jorenn92/maintainerr:latest
    container_name: maintainerr
    restart: unless-stopped
    volumes:
      - /docker/maintainerr/data:/opt/data
    environment:
      - TZ=America/Vancouver
      - PUID=1000 # chown 1000 data
      - PGID=1000
      # - DEBUG=true # uncomment to enable debug logs
      #      - BASE_PATH=/maintainerr # uncomment if you're serving maintainerr from a subdirectory
      #      - UI_HOSTNAME=:: # uncomment if you want to listen on IPv6 instead (default 0.0.0.0)
      #      - UI_PORT=6247 # uncomment to change the UI port (default 6246). Useful if you're on a network where the port is already in use
      #      - API_PORT=3002 # uncomment to change the API port (default 3001). Useful if you're on a network where the port is already in use
    ports:
      - 6246:6246
networks: {}
