services:
  plex-auto-languages:
    image: journeyover/plex-auto-languages:latest
    container_name: plex-auto-languages
    restart: unless-stopped
    environment:
      - PLEX_URL=${PLEX_URL}
      - PLEX_TOKEN=${PLEX_TOKEN}
      - TZ=America/Vancouver
    volumes:
      - /docker/plex-auto-languages/config:/config