---
services:
  whisparr:
    image: ghcr.io/thespad/whisparr:latest
    container_name: whisparr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Vancouver
    volumes:
      - ./config:/config

      - type: volume
        source: nfs_media
        target: /downloads
        volume:
          subpath: downloads

      - type: volume
        source: nfs_media
        target: /whisparr
        volume:
          subpath: j/whisparr
    ports:
      - 6969:6969

volumes:
  # Pull the infrastructure shares you defined in your volumes stack
  nfs_media:
    external: true
