services:
  lidarr:
    image: lscr.io/linuxserver/lidarr:nightly
    # image: blampe/lidarr:latest
    container_name: lidarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Vancouver
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:lidarr
      - TP_THEME=dracula
    volumes:
      - ./config:/config
      - /docker/lidarr/backups:/backups
      - /media/downloads:/downloads
      - /media/music:/music
    ports:
      - 8686:8686