---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/widgets

- resources:
    cpu: true
    memory: true
    disk: /

- search:
    provider: google
    target: _blank

- datetime:
    text_size: xl
    format:
        timeStyle: short

- openweathermap:
    label: Richmond #optional
    latitude: 49.162781
    longitude: -123.136650
    units: metric # or imperial
    provider: openweathermap
    apiKey: "{{HOMEPAGE_VAR_OPENWEATHERMAP_API_KEY}}"
    cache: 5 # Time in minutes to cache API responses, to stay within limits