services:
  bazarr:
    image: lscr.io/linuxserver/bazarr
    container_name: bazarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Vancouver
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:bazarr
      - TP_THEME=dracula
    volumes:
      # Keep local config local
      - ./config:/config

      # 1. Backups subpath from nfs_docker
      - type: volume
        source: nfs_docker
        target: /backups
        volume:
          subpath: bazarr/backups

      # 2. Movies subpath from nfs_media
      - type: volume
        source: nfs_media
        target: /movies
        volume:
          subpath: movies

      # 3. Shows subpath from nfs_media
      - type: volume
        source: nfs_media
        target: /shows
        volume:
          subpath: shows

      # 4. Anime subpath from nfs_media
      - type: volume
        source: nfs_media
        target: /anime
        volume:
          subpath: anime
    ports:
      - 6767:6767

volumes:
  # Pull the infrastructure shares you defined in your volumes stack
  nfs_docker:
    external: true
  nfs_media:
    external: true
